version: "3.9"

services:

  redis_server:
    image: redis:7.2.1-alpine
    ports:
    - "6379:6379"

    depends_on:
      - api

  api:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
    - "5000:5000"
